"""email messages: nullable campaign_contact, add sending_account and to_email

Revision ID: 89f1dbaba064
Revises: fa33b6bda29f
Create Date: 2026-09-09 00:57:45.325177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89f1dbaba064'
down_revision: Union[str, None] = 'fa33b6bda29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('sending_account_id', sa.UUID(), nullable=False))
    op.add_column('email_messages', sa.Column('to_email', sa.String(length=320), nullable=False))
    op.alter_column('email_messages', 'campaign_contact_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_email_messages_sending_account_id'), 'email_messages', ['sending_account_id'], unique=False)
    op.create_foreign_key(None, 'email_messages', 'sending_accounts', ['sending_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_messages', type_='foreignkey')
    op.drop_index(op.f('ix_email_messages_sending_account_id'), table_name='email_messages')
    op.alter_column('email_messages', 'campaign_contact_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('email_messages', 'to_email')
    op.drop_column('email_messages', 'sending_account_id')
    # ### end Alembic commands ###
