"""initial schema

Revision ID: fa33b6bda29f
Revises: 
Create Date: 2026-09-08 22:01:53.601979

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'fa33b6bda29f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('size_band', sa.String(length=64), nullable=True),
    sa.Column('careers_page_url', sa.String(length=1024), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('research_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('email_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_skeleton', sa.Text(), nullable=False),
    sa.Column('body_skeleton', sa.Text(), nullable=False),
    sa.Column('llm_instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_logs',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_entity_id'), 'event_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_logs_entity_type'), 'event_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_table('resume_variants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_family', sa.String(length=128), nullable=True),
    sa.Column('pdf_file_path', sa.String(length=1024), nullable=True),
    sa.Column('positioning_summary', sa.Text(), nullable=True),
    sa.Column('highlight_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_variants_role_family'), 'resume_variants', ['role_family'], unique=False)
    op.create_table('sending_accounts',
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('provider_type', sa.Enum('gmail_oauth', 'smtp', 'api_resend', 'api_sendgrid', name='sending_account_provider'), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('health_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppression_entries',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.Enum('opt_out', 'hard_bounce', 'manual_block', 'soft_bounce_exhausted', name='suppression_reason'), nullable=False),
    sa.Column('source', sa.Enum('system', 'user', name='suppression_source'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_entries_normalized_email'), 'suppression_entries', ['normalized_email'], unique=True)
    op.create_table('contacts',
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.Enum('csv', 'enriched', 'manual', name='contact_source'), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'risky', 'invalid', name='verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'queued', 'sent', 'opened', 'replied', 'bounced', 'opted_out', 'suppressed', name='contact_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_email', name='uq_contacts_normalized_email')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_normalized_email'), 'contacts', ['normalized_email'], unique=False)
    op.create_table('job_openings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.Enum('onsite', 'remote', 'hybrid', 'unspecified', name='work_mode'), nullable=False),
    sa.Column('experience_range', sa.String(length=128), nullable=True),
    sa.Column('batch_eligibility', sa.String(length=255), nullable=True),
    sa.Column('salary_text', sa.String(length=255), nullable=True),
    sa.Column('apply_url', sa.String(length=1024), nullable=True),
    sa.Column('source_board', sa.String(length=128), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('discovered_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'applied', 'closed', 'irrelevant', name='job_opening_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_company_id'), 'job_openings', ['company_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_opening_id', sa.UUID(), nullable=True),
    sa.Column('target_description', sa.Text(), nullable=True),
    sa.Column('resume_variant_id', sa.UUID(), nullable=False),
    sa.Column('email_template_id', sa.UUID(), nullable=False),
    sa.Column('sending_account_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('review_required', 'auto', name='campaign_mode'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='campaign_status'), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('send_window_start_local', sa.Time(), nullable=False),
    sa.Column('send_window_end_local', sa.Time(), nullable=False),
    sa.Column('send_window_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('follow_up_schedule_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.id'], ),
    sa.ForeignKeyConstraint(['resume_variant_id'], ['resume_variants.id'], ),
    sa.ForeignKeyConstraint(['sending_account_id'], ['sending_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_job_opening_id'), 'campaigns', ['job_opening_id'], unique=False)
    op.create_table('campaign_contacts',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'queued', 'sent', 'replied', 'bounced', 'opted_out', 'suppressed', 'completed', 'skipped', name='campaign_contact_status'), nullable=False),
    sa.Column('generated_email_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contacts_campaign_contact')
    )
    op.create_index(op.f('ix_campaign_contacts_campaign_id'), 'campaign_contacts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_contact_id'), 'campaign_contacts', ['contact_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('campaign_contact_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=512), nullable=True),
    sa.Column('thread_id', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_detected', sa.Boolean(), nullable=False),
    sa.Column('bounce_type', sa.Enum('none', 'soft', 'hard', name='bounce_type'), nullable=False),
    sa.Column('bounce_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_contact_id'], ['campaign_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_campaign_contact_id'), 'email_messages', ['campaign_contact_id'], unique=False)
    op.create_index(op.f('ix_email_messages_provider_message_id'), 'email_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_campaign_contact_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_campaign_contacts_contact_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_campaign_id'), table_name='campaign_contacts')
    op.drop_table('campaign_contacts')
    op.drop_index(op.f('ix_campaigns_job_opening_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_job_openings_company_id'), table_name='job_openings')
    op.drop_table('job_openings')
    op.drop_index(op.f('ix_contacts_normalized_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_suppression_entries_normalized_email'), table_name='suppression_entries')
    op.drop_table('suppression_entries')
    op.drop_table('sending_accounts')
    op.drop_index(op.f('ix_resume_variants_role_family'), table_name='resume_variants')
    op.drop_table('resume_variants')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
